# Site settings
title: POSC 1020
subtitle: Introduction to International Relations
email: svmille@clemson.edu
description: "This introductory-level course will survey several core topics in the study of international relations and its discussion in policy circles. Our approach to these topics will be targeted even though our survey of the field will be broad. We will focus our inquiries to the interests that actors have, the means by which they interact, and the institutions in which they operate that constrain or facilitate their behavior. We will take this approach, along with a broad understanding of the history of international politics, and start first with a study of the causes of conflict and war. This is our biggest question in the entirety of international relations, making it an ideal place to start. We will continue with a review of international trade, finance, and monetary policy. These topics are obtuse to lay observers but we will make sense of these topics within our approach of actors' interests, interactions, and institutions. We will close the semester with newer topics in international relations, like human rights and environmental concerns, that will shape our discussion of world politics in the years to come. By the end of the semester, students should have a deeper knowledge of international relations and, importantly, better understand current events and policy discussions."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://posc1020.svmiller.com" # the base hostname & protocol for your site
twitter_username: stevenvmiller
github_username:  svmiller
leadimage: trump-tillerson-haley.jpg
leadimage_description: "New to international relations? Not sure how things work? You're welcome to follow and learn from this intro-level course."
authorurl: "http://svmiller.com"
syllabus: "http://posc1020.svmiller.com/syllabus/posc1020-fall2018-syllabus.pdf"
githublink: "https://github.com/svmiller/posc1020"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

include: ['_images']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
